name: atxebike.com
favicon: null
layout_spectrum: 0.99472
typography_spectrum: 0.5940319506917149
title: Austin Texas electric bike rental and sales
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75440712-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#767374'
    - '#cccbcb'
    - '#969494'
    - '#262626'
  brandStrength: 0.31934181158430874
  lightness: 0.7903748063836247
  saturation: 0.544702565530315
  rhythmicContrast: 0.032118751434609294
purpose: []
